SET DEFINE OFF

INSERT INTO APARTAMENTO (NOMBRE, NUMERO, AMOBLADO, NUMERO_HABITACIONES, DIRECCION, INCLUYE_SERVICIOS, CALIFICACION) 
VALUES ('klonDificios', 'A801', 1, 3, 'Calle 60 M Numero 04 Q 79', 1, 4.2);

INSERT INTO APARTAMENTO (NOMBRE, NUMERO, AMOBLADO, NUMERO_HABITACIONES, DIRECCION, INCLUYE_SERVICIOS, CALIFICACION) 
VALUES ('klonDificios', 'A802', 1, 3, 'Calle 60 M Numero 04 Q 79', 1, 4.2);

INSERT INTO APARTAMENTO (NOMBRE, NUMERO, AMOBLADO, NUMERO_HABITACIONES, DIRECCION, INCLUYE_SERVICIOS, CALIFICACION) 
VALUES ('klonDificios', 'A803', 1, 3, 'Calle 60 M Numero 04 Q 79', 1, 4.2);

INSERT INTO APARTAMENTO (NOMBRE, NUMERO, AMOBLADO, NUMERO_HABITACIONES, DIRECCION, INCLUYE_SERVICIOS, CALIFICACION) 
VALUES ('edFenicia', 'A201', 0, 2, 'Calle 11 D Numero 29 S 99', 0, 3.7);

INSERT INTO APARTAMENTO (NOMBRE, NUMERO, AMOBLADO, NUMERO_HABITACIONES, DIRECCION, INCLUYE_SERVICIOS, CALIFICACION) 
VALUES ('edFenicia', 'A202', 0, 2, 'Calle 11 D Numero 29 S 99', 0, 3.7);

